#!/bin/bash

# Main rose interface
#
# Copyright (C) 2016  Sam Hart
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

. $ROSELIB_PATH/import.sh

import "common.sh"
import "output.sh"
import "usage.sh"

for i in "$@"
do
  case $i in
    init)
      CMD_INIT=yes
      shift
      ;;
    help)
      CMD_HELP=yes
      shift
      ;;
    -*)
      OPTIONS+=("${i#*=}")
      shift
      ;;
    *)
      PARAMETERS+=("${i#*=}")
      shift
      ;;
  esac
done

if has_option "-k"; then
  trace "YO YO YO BITCHES"
fi

if [ -n "$CMD_HELP" ]; then
  usage
  exit 0
fi

